services:
  - type: web
    name: solar-record-api
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar -Dserver.port=10000 target/*.jar
    envVars:
      - key: SERVER_PORT
        value: 10000

  - type: web
    name: solar-rts-ui
    runtime: static
    buildCommand: npm install; npm run build
    publishDirectory: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html