# DATABASE (PostgreSQL - Neon)
spring.datasource.url=jdbc:postgresql://ep-muddy-night-aohjrf7n-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_omyzDB20MCpk
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MAIL (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shantanukumbhar310@gmail.com
spring.mail.password=vjxv altu swar otcg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.thymeleaf.cache=true

# CLOUDINARY
cloudinary.url=cloudinary://871626453924828:23E0WWFVDjTqWlub5Sr9X_qEdnk@dxxqtvndg

# SERVER
server.port=${PORT:8080}
server.tomcat.max-part-count=500

# JWT
jwt.secret=solarRtsSecretKey_ChangeThis_In_Prod_123456
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
